modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="devilmod"
version="1.0.0"
displayName="Devil Mod"
authors="insideepta, rmd_pr"
logoFile="logo.png"
description='''
Did you want to understand what kind of monster is watching you?
Mod the Devil - will make up for this shortcoming.
Fight the devil free the world from the devil's attack
"You can! Believe in yourself." - 1nside_Ent4, rmd_pr

Source code: https://github.com/insiderepta/DevilMod
Discord (Russian-language channel):https://discord.gg/aH3XtBrvJz
'''

[[dependencies.devilmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.devilmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"